### ISSUE TITLE
Trouble uploading from app

### ISSUE THREAD

**Issue by jeppetrost** [intxcc/OwnTrack#1]
Hi,
I'm having some troubles with the app. Some days I'll see it -not- uploading the list of locations, but instead simply say "44 in send list" -- even if my interval was 2 or 5.
It says the server is "working" (and it has been working before!), there are no warnings.
I don't know what the issue is!?
(A workaround could be having a button on the main screen with something like "force send locations" to get rid of them).

**Comment by intxcc** [comment]
Thank you for the report! I will look into it as soon as possible.

Edit: I will look into it anyway, but you would really help me if you could post and/or send me a logcat log.
